### ISSUE TITLE
Build process completed with 3 tests failed

### ISSUE THREAD

**Issue by hernanmd** [jzimmerman/langcc#15]
I'm using macOS 11.7 first so that could be an issue? 
My environment details:

```
$ clang --version
Homebrew clang version 15.0.0
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin

$ > llvm-config --version --prefix --includedir --libdir
15.0.0
/usr/local/Cellar/llvm/15.0.0
/usr/local/Cellar/llvm/15.0.0/include
/usr/local/Cellar/llvm/15.0.0/lib

HOMEBREW_VERSION: 3.6.2-26-g4441452
ORIGIN: https://github.com/Homebrew/brew
HEAD: 4441452f4e7a7efdd5ae8cc98466d8cf6fa410ab
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 44f9ecb1cc912260152fd6221fe012dbfca1af90
Core tap last commit: 6 hours ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 4
Homebrew Ruby: 2.6.8 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/bin/ruby
CPU: quad-core 64-bit broadwell
Clang: 13.0.0 build 1300
Git: 2.37.3 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.7-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 12.5.1 => /Users/mvs/Downloads/Xcode.app/Contents/Developer
```

```
$ pkgutil --pkg-info=com.apple.pkg.CLTools_Executables | grep version
version: 13.2.0.0.1.1638488800
```

```
$ xcode-select -p
/Library/Developer/CommandLineTools
```

The build:

```
$ ./deps_macos.sh
$ make -j8

...
clang++ -c -o build/go__gen.o -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 gen/go__gen.cpp
mkdir -p build
clang++ -o build/py_standalone_test -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 src/py_standalone_test.cpp build/py__gen.o -L/opt/local/lib -L/usr/local/opt/gperftools/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -ldl -ltcmalloc
ld: warning: directory not found for option '-L/opt/local/lib'
dsymutil build/py_standalone_test
warning: (x86_64) /var/folders/hj/wvd354ps77s53v3r5tw3_6kr0000gn/T/py_standalone_test-b42d74.o unable to open object file: No such file or directory
mkdir -p build
clang++ -o build/go_standalone_test -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 src/go_standalone_test.cpp build/go__gen.o -L/opt/local/lib -L/usr/local/opt/gperftools/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -ldl -ltcmalloc
ld: warning: directory not found for option '-L/opt/local/lib'
dsymutil build/go_standalone_test
warning: (x86_64) /var/folders/hj/wvd354ps77s53v3r5tw3_6kr0000gn/T/go_standalone_test-c14e11.o unable to open object file: No such file or directory
```

Seems the problem is the "ld: warning: directory not found for option '-L/opt/local/lib'" part but the binaries were built:

```
> tree build
build
├── cc__gen.o
├── common__data_gen.o
├── data__gen.o
├── datacc
├── datacc.dSYM
│   └── Contents
│       ├── Info.plist
│       └── Resources
│           └── DWARF
│               └── datacc
├── datacc.o
├── datacc_main.o
├── gen_test_bin
│   ├── go__gen_test
│   ├── go__gen_test.dSYM
│   │   └── Contents
│   │       ├── Info.plist
│   │       └── Resources
│   │           └── DWARF
│   │               └── go__gen_test
│   ├── py__gen_test
│   └── py__gen_test.dSYM
│       └── Contents
│           ├── Info.plist
│           └── Resources
│               └── DWARF
│                   └── py__gen_test
├── go__gen.o
├── go_standalone_test
├── go_standalone_test.dSYM
│   └── Contents
│       ├── Info.plist
│       └── Resources
│           └── DWARF
│               └── go_standalone_test
├── langcc
├── langcc.dSYM
│   └── Contents
│       ├── Info.plist
│       └── Resources
│           └── DWARF
│               └── langcc
├── langcc.o
├── langcc_emit.o
├── langcc_encode.o
├── langcc_lexer.o
├── langcc_main.o
├── langcc_normalize.o
├── langcc_parser_attr.o
├── langcc_parser_cps.o
├── langcc_parser_flatten.o
├── langcc_parser_lr.o
├── meta__gen.o
├── py__gen.o
├── py_standalone_test
├── py_standalone_test.dSYM
│   └── Contents
│       ├── Info.plist
│       └── Resources
│           └── DWARF
│               └── py_standalone_test
├── unittest_lang
├── unittest_lang_main.o
├── unittest_lib
└── unittest_lib_main.o
```

The make install ran without problems

```
> sudo make install
Password:
mkdir -p /usr/local/bin
mkdir -p /usr/local/include
cp build/datacc /usr/local/bin/
cp build/langcc /usr/local/bin/
cp src/langcc_util.hpp /usr/local/include/
cp src/langcc_rt.hpp /usr/local/include/
```

Then most tests passed but 3 which failed:

```
[000:04:49.628031] [success] attr_basic1
[000:04:49.890931] [success] unreach2
[000:04:50.303145] [success] write_concat_alt2
[000:04:52.536100] [success] gen_alt_basic03
[000:05:03.958407] [success] golang_assoc_mini6
[TIMEOUT] golang_assoc_mini7_opaque[TIMEOUT] right_rec_nested_concat[TIMEOUT] golang_field_star2_succ[000:05:03.971889]
[000:05:03.971889]  ===== Summary: 82 succeeded, 3 failed.
[000:05:03.971889]
[000:05:03.972140] --  ===== Failure(timeout): golang_assoc_mini7_opaque
[000:05:03.972140]
[000:05:03.972163] --  ===== Begin stdout[golang_assoc_mini7_opaque]
[000:05:03.972163]
[000:05:03.972336]
[000:05:03.972336] --  ===== End stdout[golang_assoc_mini7_opaque]
[000:05:03.972361] --  ===== Begin stderr[golang_assoc_mini7_opaque]
[000:05:03.972361]    [000:04:49.638483] -- Performing initial validation and tabulation
[000:05:03.972361]    [000:04:49.639976] -- Compiling lexer
[000:05:03.972361]    [000:04:49.646063] -- Compiling parser: tabulating symbols
[000:05:03.972361]    [000:04:49.646272] -- Compiling parser: inferring attributes
[000:05:03.972361]    [000:04:49.649761] -- Compiling parser: symbol iteration 1 (0 triggers)
[000:05:03.972361]    [000:04:49.674939] -- SLR(1) NFA: 78 vertices, 102 edges
[000:05:03.972361]    [000:04:49.683206] -- SLR(1) subset NFA: 32 vertices, 40 edges
[000:05:03.972361]    [000:04:49.683635] -- Compiling parser: symbol iteration 2 (4 triggers)
[000:05:03.972361]    [000:04:49.716314] -- SLR(1) NFA: 102 vertices, 138 edges
[000:05:03.972361]    [000:04:49.731255] -- SLR(1) subset NFA: 41 vertices, 64 edges
[000:05:03.972361]    [000:04:49.731744] -- Compiling parser: symbol iteration 3 (8 triggers)
[000:05:03.972361]    [000:04:49.764352] -- SLR(1) NFA: 103 vertices, 135 edges
[000:05:03.972361]    [000:04:49.782810] -- SLR(1) subset NFA: 42 vertices, 71 edges
[000:05:03.972361]    [000:04:49.785625] -- Compiling parser: final lookaheads
[000:05:03.972361]    [000:04:49.802990] -- Compiling parser: constructing LR NFA
[000:05:03.972361]    [000:04:49.814310] -- Compiling parser: LR NFA subset construction
[000:05:03.972361]    [000:04:49.829737] -- Compiling parser: no LR conflicts
[000:05:03.972361]    [000:04:49.829837] -- LR NFA: 103 vertices, 135 edges
[000:05:03.972361]    [000:04:49.829887] -- LR DFA: 42 vertices, 71 edges
[000:05:03.972361]    [000:04:49.834801] -- Generating AST datatype definitions
[000:05:03.972361]    [000:04:49.963097] -- Generating AST writer definitions
[000:05:03.972361]    [000:04:49.968080] -- Generating AST parser definitions
[000:05:03.972361]    [000:04:50.087304] -- Generating global definitions
[000:05:03.972361]    [000:04:50.130529] -- Running: clang++ -D __MACOS__ -D __MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o build/gen_test_bin/golang_assoc_mini7_opaque__gen_test -g -ggdb -g3 -std=c++17 -fno-omit-frame-pointer -mmacosx-version-min=12.0 -ldl -I ./build/gen_test_src -I ./src build/gen_test_src/golang_assoc_mini7_opaque__gen.cpp build/gen_test_src/golang_assoc_mini7_opaque__gen_test.cpp
[000:05:03.972361]
[000:05:03.972628] --  ===== End stderr[golang_assoc_mini7_opaque]
[000:05:03.972656] --  ===== Failure(timeout): golang_field_star2_succ
[000:05:03.972656]
[000:05:03.972677] --  ===== Begin stdout[golang_field_star2_succ]
[000:05:03.972677]
[000:05:03.972696] --  ===== End stdout[golang_field_star2_succ]
[000:05:03.972714] --  ===== Begin stderr[golang_field_star2_succ]
[000:05:03.972714]    [000:04:52.543648] -- Performing initial validation and tabulation
[000:05:03.972714]    [000:04:52.545163] -- Compiling lexer
[000:05:03.972714]    [000:04:52.550179] -- Compiling parser: tabulating symbols
[000:05:03.972714]    [000:04:52.550434] -- Compiling parser: inferring attributes
[000:05:03.972714]    [000:04:52.551872] -- Compiling parser: symbol iteration 1 (0 triggers)
[000:05:03.972714]    [000:04:52.558818] -- SLR(1) NFA: 30 vertices, 29 edges
[000:05:03.972714]    [000:04:52.561307] -- SLR(1) subset NFA: 20 vertices, 19 edges
[000:05:03.972714]    [000:04:52.561520] -- Compiling parser: symbol iteration 2 (2 triggers)
[000:05:03.972714]    [000:04:52.568145] -- SLR(1) NFA: 32 vertices, 31 edges
[000:05:03.972714]    [000:04:52.570685] -- SLR(1) subset NFA: 20 vertices, 19 edges
[000:05:03.972714]    [000:04:52.571452] -- Compiling parser: final lookaheads
[000:05:03.972714]    [000:04:52.574728] -- Compiling parser: constructing LR NFA
[000:05:03.972714]    [000:04:52.577612] -- Compiling parser: LR NFA subset construction
[000:05:03.972714]    [000:04:52.580907] -- Compiling parser: no LR conflicts
[000:05:03.972714]    [000:04:52.581012] -- LR NFA: 32 vertices, 31 edges
[000:05:03.972714]    [000:04:52.581067] -- LR DFA: 20 vertices, 19 edges
[000:05:03.972714]    [000:04:52.582440] -- Generating AST datatype definitions
[000:05:03.972714]    [000:04:52.701561] -- Generating AST writer definitions
[000:05:03.972714]    [000:04:52.704663] -- Generating AST parser definitions
[000:05:03.972714]    [000:04:52.733748] -- Generating global definitions
[000:05:03.972714]    [000:04:52.754709] -- Running: clang++ -D __MACOS__ -D __MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o build/gen_test_bin/golang_field_star2_succ__gen_test -g -ggdb -g3 -std=c++17 -fno-omit-frame-pointer -mmacosx-version-min=12.0 -ldl -I ./build/gen_test_src -I ./src build/gen_test_src/golang_field_star2_succ__gen.cpp build/gen_test_src/golang_field_star2_succ__gen_test.cpp
[000:05:03.972714]
[000:05:03.972989] --  ===== End stderr[golang_field_star2_succ]
[000:05:03.973017] --  ===== Failure(timeout): right_rec_nested_concat
[000:05:03.973017]
[000:05:03.973041] --  ===== Begin stdout[right_rec_nested_concat]
[000:05:03.973041]
[000:05:03.973061] --  ===== End stdout[right_rec_nested_concat]
[000:05:03.973080] --  ===== Begin stderr[right_rec_nested_concat]
[000:05:03.973080]    [000:04:50.308527] -- Performing initial validation and tabulation
[000:05:03.973080]    [000:04:50.310751] -- Compiling lexer
[000:05:03.973080]    [000:04:50.315677] -- Compiling parser: tabulating symbols
[000:05:03.973080]    [000:04:50.315891] -- Compiling parser: inferring attributes
[000:05:03.973080]    [000:04:50.317060] -- Compiling parser: symbol iteration 1 (0 triggers)
[000:05:03.973080]    [000:04:50.322055] -- SLR(1) NFA: 22 vertices, 22 edges
[000:05:03.973080]    [000:04:50.324101] -- SLR(1) subset NFA: 15 vertices, 15 edges
[000:05:03.973080]    [000:04:50.324791] -- Compiling parser: final lookaheads
[000:05:03.973080]    [000:04:50.327382] -- Compiling parser: constructing LR NFA
[000:05:03.973080]    [000:04:50.329500] -- Compiling parser: LR NFA subset construction
[000:05:03.973080]    [000:04:50.331776] -- Compiling parser: no LR conflicts
[000:05:03.973080]    [000:04:50.331879] -- LR NFA: 22 vertices, 22 edges
[000:05:03.973080]    [000:04:50.331936] -- LR DFA: 15 vertices, 15 edges
[000:05:03.973080]    [000:04:50.333164] -- Generating AST datatype definitions
[000:05:03.973080]    [000:04:50.474111] -- Generating AST writer definitions
[000:05:03.973080]    [000:04:50.478388] -- Generating AST parser definitions
[000:05:03.973080]    [000:04:50.498812] -- Generating global definitions
[000:05:03.973080]    [000:04:50.519858] -- Running: clang++ -D __MACOS__ -D __MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o build/gen_test_bin/right_rec_nested_concat__gen_test -g -ggdb -g3 -std=c++17 -fno-omit-frame-pointer -mmacosx-version-min=12.0 -ldl -I ./build/gen_test_src -I ./src build/gen_test_src/right_rec_nested_concat__gen.cpp build/gen_test_src/right_rec_nested_concat__gen_test.cpp
[000:05:03.973080]
[000:05:03.973279] --  ===== End stderr[right_rec_nested_concat]
[000:05:03.973304]
[000:05:03.973304]  ===== Summary: 82 succeeded, 3 failed.
[000:05:03.973304]
[000:05:03.973367] Succeeded:
[000:05:03.973391]   arith1_prec1
[000:05:03.973408]   arith_naive2_alt
[000:05:03.973423]   arith_prec1
[000:05:03.973440]   attr_basic1
[000:05:03.973454]   attr_cps
[000:05:03.973469]   attr_iter_cps2
[000:05:03.973483]   attr_nested_pos1b
[000:05:03.973496]   attr_nested_pos1c
[000:05:03.973511]   attr_nested_pos2
[000:05:03.973525]   attr_nested_pos3
[000:05:03.973538]   attr_nested_pos4
[000:05:03.973551]   attr_predict_multi
[000:05:03.973566]   attr_single
[000:05:03.973580]   basic_a
[000:05:03.973595]   basic_ab_concat
[000:05:03.973610]   basic_block_comment1
[000:05:03.973624]   basic_cps1
[000:05:03.973638]   basic_cps2b
[000:05:03.973651]   basic_optional
[000:05:03.973664]   basic_parens
[000:05:03.973677]   basic_rep_list1
[000:05:03.973691]   basic_rep_list6
[000:05:03.973704]   basic_rep_list7
[000:05:03.973718]   basic_rep_nonzero
[000:05:03.973733]   comment
[000:05:03.973747]   cpp_sub_prec_unary2
[000:05:03.973762]   cpp_sub_typed_decl1
[000:05:03.973776]   expr_alias_name1
[000:05:03.973791]   flatten_basic01
[000:05:03.973805]   gen_alt_basic02
[000:05:03.973820]   gen_alt_basic03
[000:05:03.973834]   gen_alt_basic04
[000:05:03.973849]   gen_alt_basic05
[000:05:03.973865]   gen_alt_basic08
[000:05:03.973878]   gen_alt_basic09
[000:05:03.973893]   golang_assoc_mini2_space1
[000:05:03.973909]   golang_assoc_mini3
[000:05:03.973924]   golang_assoc_mini4
[000:05:03.973940]   golang_assoc_mini5
[000:05:03.973954]   golang_assoc_mini6
[000:05:03.973969]   golang_assoc_mini7_alias1
[000:05:03.973986]   golang_chan
[000:05:03.974001]   golang_field_star1
[000:05:03.974016]   golang_if_func_assoc2
[000:05:03.974031]   ident_ab_kw
[000:05:03.974046]   inline_nested2
[000:05:03.974061]   inline_perf1a
[000:05:03.974078]   inline_perf2a
[000:05:03.974093]   left_rec
[000:05:03.974107]   left_rec_01_mutual
[000:05:03.974122]   left_rec_03_mutual_quasi
[000:05:03.974138]   left_rec_04_prec_basic
[000:05:03.974156]   left_rec_nested
[000:05:03.974170]   lexer_adv00_pop_emit
[000:05:03.974185]   lexer_adv01_match_history
[000:05:03.974203]   lexer_adv02_match_history
[000:05:03.974219]   mem_branch2
[000:05:03.974233]   mem_branch3
[000:05:03.974246]   mem_branch4
[000:05:03.974260]   mem_branch5
[000:05:03.974275]   mem_branch_iter
[000:05:03.974289]   mem_branch_multi1
[000:05:03.974304]   prec_attr_ctx2
[000:05:03.974320]   prec_basic_paren_fail
[000:05:03.974337]   prec_basic_succ1
[000:05:03.974351]   prec_large
[000:05:03.974365]   prec_mixed_fixity2_rev
[000:05:03.974381]   prec_mixed_fixity3_fail
[000:05:03.974398]   prec_with_attr1
[000:05:03.974412]   rep2
[000:05:03.974426]   repcount
[000:05:03.974441]   right_rec_alt
[000:05:03.974455]   unreach1
[000:05:03.974469]   unreach2
[000:05:03.974484]   write_concat_alt1
[000:05:03.974499]   write_concat_alt2
[000:05:03.974514]   ws_sig_01_comment_lit
[000:05:03.974530]   xfail_conflict_sub
[000:05:03.974544]   xfail_lexer_conflict
[000:05:03.974559]   xfail_lexer_multi_push
[000:05:03.974577]   xfail_parser_compound_id
[000:05:03.974593]   xfail_parser_non_lr
[000:05:03.974615]
[000:05:03.974615] Failed:
[000:05:03.974631]   golang_assoc_mini7_opaque
[000:05:03.974648]   golang_field_star2_succ
[000:05:03.974815]   right_rec_nested_concat
```

Didn't tried to generate something yet.
Any suggestions should I check?

**Comment by jzimmerman** [comment]
Looks like the tests are failing due to timing out. I've just pushed e74d4bc which should extend the timeout - let me know if that fixes the issue.

**Comment by hernanmd** [comment]
Ok, I pulled and tried again. The make still show the warnings. The bootstrap script enters in an infinite loop:

```
mkstemps stdin: Too many open files
 *** Return code: mkstemps stdin: -1
mkstemps stdin: Too many open files
 *** Return code: mkstemps stdin: -1
...and so on
```

I had to terminate the iTerm process (Ctrl+C won't work).
I checked twice, second time only iTerm open.

**Comment by jzimmerman** [comment]
Can you pull the latest and try again?

Also, if it still fails, try running a single one of the failing tests in isolation:
```build/unittest_lang golang_assoc_mini7_opaque```

**Comment by hernanmd** [comment]
Ok, the first time I ran I've hit probably a clang bug: 

```
> make -j8
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/datacc_main.o src/datacc_main.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/datacc.o src/datacc.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/cc__gen.o gen/cc__gen.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/data__gen.o gen/data__gen.cpp
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -o build/datacc build/datacc_main.o build/datacc.o build/cc__gen.o build/data__gen.o  -L/opt/local/lib -L/usr/local/opt/gperftools/lib -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -ldl -ltcmalloc
ld: warning: directory not found for option '-L/opt/local/lib'
dsymutil build/datacc
build/datacc src/common.data gen
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/langcc_main.o src/langcc_main.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/langcc.o src/langcc.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/langcc_lexer.o src/langcc_lexer.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/langcc_parser_flatten.o src/langcc_parser_flatten.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/langcc_parser_attr.o src/langcc_parser_attr.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/langcc_parser_cps.o src/langcc_parser_cps.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/langcc_parser_lr.o src/langcc_parser_lr.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/langcc_encode.o src/langcc_encode.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/langcc_normalize.o src/langcc_normalize.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/langcc_emit.o src/langcc_emit.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/meta__gen.o gen/meta__gen.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/common__data_gen.o gen/common__data_gen.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/unittest_lib_main.o src/unittest_lib_main.cpp
mkdir -p build
clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/unittest_lang_main.o src/unittest_lang_main.cpp
PLEASE submit a bug report to https://github.com/Homebrew/homebrew-core/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/unittest_lang_main.o src/unittest_lang_main.cpp
1.	<eof> parser at end of file
2.	Code generation
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM.dylib            0x0000000113b55a3a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 42
1  libLLVM.dylib            0x0000000113b54b08 llvm::sys::CleanupOnSignal(unsigned long) + 200
2  libLLVM.dylib            0x0000000117609feb (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) + 75
3  libLLVM.dylib            0x0000000117609f61 CrashRecoverySignalHandler(int) + 113
4  libsystem_platform.dylib 0x00007fff20430d7d _sigtramp + 29
5  libLLVM.dylib            0x0000000113b25590 llvm::raw_svector_ostream::write_impl(char const*, unsigned long) + 96
6  libLLVM.dylib            0x000000011464c588 llvm::DwarfUnit::constructSubprogramArguments(llvm::DIE&, llvm::DITypeRefArray) + 152
7  libLLVM.dylib            0x000000011464c826 llvm::DwarfUnit::applySubprogramAttributes(llvm::DISubprogram const*, llvm::DIE&, bool) + 550
8  libLLVM.dylib            0x00000001146466cb llvm::DwarfUnit::getOrCreateSubprogramDIE(llvm::DISubprogram const*, bool) + 555
9  libLLVM.dylib            0x0000000114647dbe llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DICompositeType const*) + 398
10 libLLVM.dylib            0x0000000114646f42 llvm::DwarfUnit::createTypeDIE(llvm::DIScope const*, llvm::DIE&, llvm::DIType const*) + 162
11 libLLVM.dylib            0x000000011464a3f8 llvm::DwarfUnit::constructMemberDIE(llvm::DIE&, llvm::DIDerivedType const*) + 200
12 libLLVM.dylib            0x0000000114647e01 llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DICompositeType const*) + 465
13 libLLVM.dylib            0x0000000114646f42 llvm::DwarfUnit::createTypeDIE(llvm::DIScope const*, llvm::DIE&, llvm::DIType const*) + 162
14 libLLVM.dylib            0x00000001146488f2 llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DIDerivedType const*) + 162
15 libLLVM.dylib            0x0000000114646f10 llvm::DwarfUnit::createTypeDIE(llvm::DIScope const*, llvm::DIE&, llvm::DIType const*) + 112
16 libLLVM.dylib            0x00000001146488f2 llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DIDerivedType const*) + 162
17 libLLVM.dylib            0x0000000114646f10 llvm::DwarfUnit::createTypeDIE(llvm::DIScope const*, llvm::DIE&, llvm::DIType const*) + 112
18 libLLVM.dylib            0x00000001146488f2 llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DIDerivedType const*) + 162
19 libLLVM.dylib            0x0000000114646f10 llvm::DwarfUnit::createTypeDIE(llvm::DIScope const*, llvm::DIE&, llvm::DIType const*) + 112
20 libLLVM.dylib            0x000000011464c588 llvm::DwarfUnit::constructSubprogramArguments(llvm::DIE&, llvm::DITypeRefArray) + 152
21 libLLVM.dylib            0x000000011464c826 llvm::DwarfUnit::applySubprogramAttributes(llvm::DISubprogram const*, llvm::DIE&, bool) + 550
22 libLLVM.dylib            0x00000001146466cb llvm::DwarfUnit::getOrCreateSubprogramDIE(llvm::DISubprogram const*, bool) + 555
23 libLLVM.dylib            0x0000000114647dbe llvm::DwarfUnit::constructTypeDIE(llvm::DIE&, llvm::DICompositeType const*) + 398
24 libLLVM.dylib            0x0000000114646f42 llvm::DwarfUnit::createTypeDIE(llvm::DIScope const*, llvm::DIE&, llvm::DIType const*) + 162
25 libLLVM.dylib            0x0000000114610cd6 llvm::DwarfCompileUnit::getOrCreateGlobalVariableDIE(llvm::DIGlobalVariable const*, llvm::ArrayRef<llvm::DwarfCompileUnit::GlobalExpr>) + 470
26 libLLVM.dylib            0x000000011461c00a llvm::DwarfDebug::beginModule(llvm::Module*) + 2858
27 libLLVM.dylib            0x00000001145e85f8 llvm::AsmPrinter::doInitialization(llvm::Module&) + 5368
28 libLLVM.dylib            0x0000000116c05034 llvm::X86AsmPrinter::doInitialization(llvm::Module&) + 100
29 libLLVM.dylib            0x0000000113d0f7cd llvm::FPPassManager::doInitialization(llvm::Module&) + 45
30 libLLVM.dylib            0x0000000113d1893e llvm::legacy::PassManagerImpl::run(llvm::Module&) + 462
31 libclang-cpp.dylib       0x00000001108aff4e clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>) + 7198
32 libclang-cpp.dylib       0x0000000110c90d34 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) + 2052
33 libclang-cpp.dylib       0x000000010f4921c3 clang::ParseAST(clang::Sema&, bool, bool) + 851
34 libclang-cpp.dylib       0x00000001113ca97b clang::FrontendAction::Execute() + 75
35 libclang-cpp.dylib       0x000000011133e9d0 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 704
36 libclang-cpp.dylib       0x00000001114180fe clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 526
37 clang++                  0x000000010f2bf695 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 2533
38 clang++                  0x000000010f2bdb4a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) + 266
39 libclang-cpp.dylib       0x0000000110f77a47 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const::$_1>(long) + 23
40 libLLVM.dylib            0x0000000113a6098b llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 235
41 libclang-cpp.dylib       0x0000000110f7790a clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const + 298
42 libclang-cpp.dylib       0x0000000110f2a536 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const + 1014
43 libclang-cpp.dylib       0x0000000110f2a810 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&, bool) const + 112
44 libclang-cpp.dylib       0x0000000110f744f2 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&) + 274
45 clang++                  0x000000010f2bcbff clang_main(int, char**) + 11903
46 libdyld.dylib            0x00007fff20406f3d start + 1
47 libdyld.dylib            0x0000000000000012 start + 18446603339975069910
clang-15: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Homebrew clang version 15.0.0
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
clang-15: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /var/folders/hj/wvd354ps77s53v3r5tw3_6kr0000gn/T/unittest_lang_main-0c474d.cpp
clang-15: note: diagnostic msg: /var/folders/hj/wvd354ps77s53v3r5tw3_6kr0000gn/T/unittest_lang_main-0c474d.sh
clang-15: note: diagnostic msg: Crash backtrace is located in
clang-15: note: diagnostic msg: /Users/mvs/Library/Logs/DiagnosticReports/clang-15_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang-15: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang-15: note: diagnostic msg:

********************
make: *** [build/unittest_lang_main.o] Error 1
make: *** Waiting for unfinished jobs....
PLEASE submit a bug report to https://github.com/Homebrew/homebrew-core/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang++ -I./src -I./gen -g -ggdb -g3 -O3 -std=c++17 -fno-omit-frame-pointer -D__HAS_LLVM_SYMBOLIZER__ -D__LLVM_SYMBOLIZER_PATH__=/usr/local/opt/llvm/bin/llvm-symbolizer -D__MACOS__ -D__MACOS_SDKROOT__=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -c -o build/langcc_emit.o src/langcc_emit.cpp
1.	<eof> parser at end of file
2.	Optimizer
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  libLLVM.dylib            0x0000000110864a3a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) + 42
1  libLLVM.dylib            0x0000000110863b08 llvm::sys::CleanupOnSignal(unsigned long) + 200
2  libLLVM.dylib            0x0000000114318feb (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) + 75
3  libLLVM.dylib            0x0000000114318f61 CrashRecoverySignalHandler(int) + 113
4  libsystem_platform.dylib 0x00007fff20430d7d _sigtramp + 29
5  libsystem_platform.dylib 000000000000000000 _sigtramp + 18446603339974898336
6  libLLVM.dylib            0x000000011184aae7 llvm::InstCombinerImpl::visitAllocSite(llvm::Instruction&) + 135
7  libLLVM.dylib            0x000000011180ace2 llvm::InstVisitor<llvm::InstCombinerImpl, llvm::Instruction*>::visit(llvm::Instruction&) + 48706
8  libLLVM.dylib            0x00000001117ef9a8 combineInstructionsOverFunction(llvm::Function&, llvm::InstructionWorklist&, llvm::AAResults*, llvm::AssumptionCache&, llvm::TargetLibraryInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::OptimizationRemarkEmitter&, llvm::BlockFrequencyInfo*, llvm::ProfileSummaryInfo*, unsigned int, llvm::LoopInfo*) + 10312
9  libLLVM.dylib            0x0000000113e807f8 llvm::detail::PassModel<llvm::Function, llvm::InstCombinePass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) + 792
10 libLLVM.dylib            0x0000000112bab319 llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) + 1769
11 libLLVM.dylib            0x0000000111f9047e llvm::CGSCCToFunctionPassAdaptor::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) + 1022
12 libLLVM.dylib            0x0000000112baa9d2 llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::CGSCCToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) + 18
13 libLLVM.dylib            0x0000000111cc98c5 llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::PassManager<llvm::LazyCallGraph::SCC, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) + 1685
14 libLLVM.dylib            0x0000000111f8e25f llvm::DevirtSCCRepeatedPass::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) + 479
15 libLLVM.dylib            0x0000000111cc8ec2 llvm::detail::PassModel<llvm::LazyCallGraph::SCC, llvm::DevirtSCCRepeatedPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&>::run(llvm::LazyCallGraph::SCC&, llvm::AnalysisManager<llvm::LazyCallGraph::SCC, llvm::LazyCallGraph&>&, llvm::LazyCallGraph&, llvm::CGSCCUpdateResult&) + 18
16 libLLVM.dylib            0x0000000111f8cdc2 llvm::ModuleToPostOrderCGSCCPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 2546
17 libLLVM.dylib            0x0000000111cc9102 llvm::detail::PassModel<llvm::Module, llvm::ModuleToPostOrderCGSCCPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 18
18 libLLVM.dylib            0x0000000110a58982 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 418
19 libLLVM.dylib            0x0000000111cc8ae1 llvm::ModuleInlinerWrapperPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 673
20 libLLVM.dylib            0x0000000113e8a652 llvm::detail::PassModel<llvm::Module, llvm::ModuleInlinerWrapperPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 18
21 libLLVM.dylib            0x0000000110a58982 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) + 418
22 libclang-cpp.dylib       0x000000010d5c76b6 (anonymous namespace)::EmitAssemblyHelper::RunOptimizationPipeline(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>&, std::__1::unique_ptr<llvm::ToolOutputFile, std::__1::default_delete<llvm::ToolOutputFile>>&) + 10246
23 libclang-cpp.dylib       0x000000010d5c1c42 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>) + 6418
24 libclang-cpp.dylib       0x000000010d9a2d34 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) + 2052
25 libclang-cpp.dylib       0x000000010c1a41c3 clang::ParseAST(clang::Sema&, bool, bool) + 851
26 libclang-cpp.dylib       0x000000010e0dc97b clang::FrontendAction::Execute() + 75
27 libclang-cpp.dylib       0x000000010e0509d0 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 704
28 libclang-cpp.dylib       0x000000010e12a0fe clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 526
29 clang++                  0x0000000108e99695 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 2533
30 clang++                  0x0000000108e97b4a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) + 266
31 libclang-cpp.dylib       0x000000010dc89a47 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const::$_1>(long) + 23
32 libLLVM.dylib            0x000000011076f98b llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) + 235
33 libclang-cpp.dylib       0x000000010dc8990a clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const + 298
34 libclang-cpp.dylib       0x000000010dc3c536 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const + 1014
35 libclang-cpp.dylib       0x000000010dc3c810 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&, bool) const + 112
36 libclang-cpp.dylib       0x000000010dc864f2 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&) + 274
37 clang++                  0x0000000108e96bff clang_main(int, char**) + 11903
38 libdyld.dylib            0x00007fff20406f3d start + 1
clang-15: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Homebrew clang version 15.0.0
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /usr/local/opt/llvm/bin
clang-15: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-15: note: diagnostic msg: /var/folders/hj/wvd354ps77s53v3r5tw3_6kr0000gn/T/langcc_emit-6f3816.cpp
clang-15: note: diagnostic msg: /var/folders/hj/wvd354ps77s53v3r5tw3_6kr0000gn/T/langcc_emit-6f3816.sh
clang-15: note: diagnostic msg: Crash backtrace is located in
clang-15: note: diagnostic msg: /Users/mvs/Library/Logs/DiagnosticReports/clang-15_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang-15: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang-15: note: diagnostic msg:
```

But after closing all programs and running again it worked nicely and all tests pass.
Now going to experiment a bit.

Thank you!
